site_name: My Docs
site_url: https://shanliao420.github.io
theme:
   name: material
   palette:
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
         primary: black
         scheme: slate
         toggle:
         icon: material/brightness-4
         name: Switch to light mode
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
         primary: white
         scheme: default
         toggle:
         icon: material/brightness-7
         name: Switch to dark mode


