site_name: shanliao documents
site_url: https://shanliao420.github.io
theme:
   name: material
   logo: assets/logo.png
   favicon: assets/favicon.png
   custom_dir: overrides
   features:
      - navigation.tabs
      - navigation.instant
   palette:
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        primary: black
        scheme: slate
        toggle:
         icon: material/brightness-4
         name: Switch to light mode
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        primary: white
        scheme: default
        toggle:
         icon: material/brightness-7
         name: Switch to dark mode
   font:
      text: Source Code Pro
      code: Source Code Pro

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences